### PR TITLE
Statistic page

### PR DESCRIPTION
**Pull request by David-Pixeln**
In InformationPage

- Added a statistic page with cards that can hold images and text information

In App

- Added a way to create pages with Router from "react-router-dom"

### CODE REVIEW

**Comment by David-Pixeln** [comment]
Accepta inte denna ännu, försöker fixa merge conflicts, och blev lite confused

**Comment by David-Pixeln** [comment]
Now it should be fine to merge!

**Review by erikpersson0884 — COMMENTED** [review]
images should be in assets folder, otherwise well done

**Review by erikpersson0884 — APPROVED** [review]
now it looks good

**Pull request merged**
